### PR TITLE
Topic/sun stars case

### PR DESCRIPTION
**Pull request by TimSylvester-mousebird**
:tada: 

Relevant to #1374

### CODE REVIEW

**Comment by mousebird** [comment]
Man.  It really feels like 3.x is complete.

**Comment by TimSylvester-mousebird** [comment]
No stars

**Review by mousebird — APPROVED** [review]
Not totally sure about the separate .metal file.  The problem is that Cocoapods doesn't pick these up, so I just tell users to import them directly.  So I've been putting everything in the default Metal file.

Looks solid, though!

**Comment by TimSylvester-mousebird** [comment]
@akovalov  No, particle systems and calculation shaders aren't set up yet.  We may do something with `MaplyPoints` in the meantime, but haven't done so yet.

**Pull request merged**
