### PR TITLE
Catalyst

### PR DESCRIPTION
**Pull request by zflamig**
WIP for supporting Mac Catalyst.

Replaces libTess with libTess2 since libTess2 doesn't use OpenGL primitives. However its not working right just yet. I might be missing something about how the output from that function is suppose to work.

Catalyst doesn't have Shared mode for heaps either so we just flag it off like for the simulator.

Catalyst also didn't like mixing Objective-C & Objective-C++... switched everything to Objective-C++

### CODE REVIEW

**Comment by mousebird** [comment]
That's interesting.  I've been curious about this for a while.
Let us know if you sort out the Tesselation issue.

**Comment by zflamig** [comment]
I think I have the Tesselation working now. Or at least things look visually correct to me again

**Comment by zflamig** [comment]
For sure. I've discovered a couple more catalyst specific things too. I think the Globe view may have another Shared memory usage that isn't gated. And I needed to add a clearColor to R16Sints.

**Comment by mousebird** [comment]
How did this end up working out?

**Comment by zflamig** [comment]
This works great! I haven't seen any issues with it so far

**Comment by TimSylvester-mousebird** [comment]
I pulled this in and rebased it on top of our latest develop branch.  Aside from a few minor conflicts, I had to fix some things around rendering into textures for `backgroundAllPoly` mode (hybrid globe rendering), but otherwise it seems to be working pretty well.  @zflamig are there any new issues that you're aware of since June?

**Comment by mousebird** [comment]
Tim used yours as a starting point.  Catalyst support should now be working in develop!
Thanks for getting the ball rolling on this.

**Comment by zflamig** [comment]
Thanks! Just rebased on this is working great for me.

**Pull request closed without merging**
