### PR TITLE
Make height animation seem more linear

### PR DESCRIPTION
**Pull request by TimSylvester-mousebird**
https://user-images.githubusercontent.com/71895881/135181785-70e83267-32de-4780-bfb2-54a303f3c55d.mp4

https://user-images.githubusercontent.com/71895881/135181801-0bc14019-85a9-45fe-a51f-91169bffdfc1.mp4

https://user-images.githubusercontent.com/71895881/135181818-66046251-eeb2-414a-a148-1602e3308bb3.mp4

https://user-images.githubusercontent.com/71895881/135181835-308eae8b-4b32-479e-b547-22ed0efe160b.mp4

### CODE REVIEW

**Review by mousebird — APPROVED** [review]
I like how it looks!
One issue though, is if users are depending on the old behavior.
Should be offer this as an option or possibly the old version as an option?

**Comment by TimSylvester-mousebird** [comment]
Easy enough, if you think it's worthwhile.  I figured it's unlikely to be important to anyone, or directly tied to anything that would break, but I guess it's possible.  I was considering letting the app set an arbitrary easing function, like [one of these](https://easings.net/).

**Comment by mousebird** [comment]
That'd be neat!
Maybe just provide the old default as an option.  But change it to the new default.

**Comment by TimSylvester-mousebird** [comment]
I had to pass it to all the gestures anyway, so I went ahead and made it a callback rather than just a flag, and updated the test cases so there's an easy copy/paste if you want to make it work the old way.

https://user-images.githubusercontent.com/71895881/135347944-d1e14d1c-0974-424f-8167-aff1243d873a.mp4

**Comment by mousebird** [comment]
Thanks!

**Pull request merged**
