### PR TITLE
[iOS] Build script for .xcframework + project imports changes

### PR DESCRIPTION
**Pull request by ldomaradzki**
I tried to use 3.3 and 3.4 release that you provide (in .framework format), but both don't work even with a simple empty project. 

This is my approach and changes to create universal .xcframework that works out of the box even with newest Xcodes.
Autotester is broken atm, didn't have time to properly look at it. Main library project still compiles without any problems (the same if you add library project as a dependency and use its build output to run it from source).

### CODE REVIEW

**Comment by akovalov** [comment]
Similar to @ldomaradzki I've tried to add framework via both CocoaPods and precompiled .framework that is provided - nothing works and gives build errors. It's on Xcode 13.2. Latest Xcode requires .xcframework.

Here is some article on this Breaking Changes with Xcode 12 and XCFramework https://blog.embrace.io/xcode-12-and-xcframework/

I've ended up that had a correct xcframework built from source but the errors with with not found .h files was still there. It was needed to move headers like in this PR. So I've used the @ldomaradzki fork for xcframework to build a .xcframework form the source and now it works. It also does not require adding search path and bridging header in build settings like described in https://mousebird-consulting-inc.github.io/WhirlyGlobe/tutorial/ios/building_from_binary.html.

Hope that it would be possible to migrate to xcframework in the next release so it can be successfully installed via CocoaPods or prebuilt binary. 

Thank you all for your hard work!

**Comment by mousebird** [comment]
We have an overhead sprint coming up here soon so we'll probably look into this.

**Comment by TimSylvester-mousebird** [comment]
Was able to merge this into the latest develop with only a few minor conflicts, but it produces a huge number of errors and warnings.  (Xcode 13.2.1)

Adding a "control/" prefix to the imports in the framework bridging header fixes the errors in the framework, but not AutoTester.  

Fixing the warnings as recommended (replacing quotes with angle brackets) creates many new errors:  "Include of non-modular header inside framework module"

**Comment by mousebird** [comment]
Ah, that madness again.

**Comment by TimSylvester-mousebird** [comment]
@akovalov Check out #1493, I think we're just about there.

**Comment by akovalov** [comment]
@TimSylvester-mousebird looks like this PR can be closed already.

**Comment by TimSylvester-mousebird** [comment]
Closing, superseded by #1493.  Thanks for getting it started!

The CI build is using `buildXCFramework` now, and producing:

[https://whirlyglobemaplydistribution.s3-us-west-1.amazonaws.com/WhirlyGlobe_Maply_Develop_latest.xcframework.zip](https://whirlyglobemaplydistribution.s3-us-west-1.amazonaws.com/WhirlyGlobe_Maply_Develop_latest.xcframework.zip)

**Pull request closed without merging**
