### PR TITLE
Topic/xcframework

### PR DESCRIPTION
**Pull request by TimSylvester-mousebird**
More progress on xcframework.  The main issue seems to be that many of the framework headers were including non-framework headers (mostly from `WhirlyGlobeLib`), which is no longer acceptable.  After moving all that stuff to private headers and updating all the include statements, I was able to get it to build cleanly.

Currently it's working embedded in the AutoTester project and as a Cocoapod. And `buildXCFramework.sh` produces `Archive Succeeded`, but I haven't yet tested the result.

### CODE REVIEW

**Comment by ivan-avalos** [comment]
This couldn't have been more coincidental, as it was only minutes ago when I figured out that the Xcode failed when I added the .framework file following the tutorial instructions, and found [this thread on StackOverflow](https://stackoverflow.com/questions/65303304), so I did a search on WhirlyGlobe's issue tracker and found this pull request posted tomorrow. Lol.

**Comment by akovalov** [comment]
@TimSylvester-mousebird great work! I've tried to build xcframework from this branch and use in the project - works good. However, found one issue while tapping on the map
```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[MaplyTapMessage setWorldLoc:]: unrecognized selector sent to instance 0x280743d20'
terminating with uncaught exception of type NSException
```
Probably because this propery moved from `MaplyTapMessage.h` to private header `MaplyTapMessage_private.h`
```
@property (nonatomic,assign) WhirlyKit::Point3f worldLoc;
```

**Comment by akovalov** [comment]
@TimSylvester-mousebird tried with CocoaPods here is a build error that there is different header files with the same name.

```
pod 'WhirlyGlobe', :git => 'https://github.com/mousebird-consulting-inc/WhirlyGlobe.git', :branch => 'topic/xcframework'
```
Screenshot 2022-01-28 at 12 29 22

**Comment by TimSylvester-mousebird** [comment]
Yeah, I've been working around that for a while, time to fix it, I guess.

Unfortunately, this seems to rely on settings in the referencing Podfile, particularly `use_frameworks!~ and `:modular_headers => true`, which is going to cause trouble with at least one client.

One potential solution is [cocoapods-packager](https://github.com/CocoaPods/cocoapods-packager), but it only seems to operate on spec repos, so I wasn't able to test it out.

**Comment by TimSylvester-mousebird** [comment]
Turns out the private properties didn't actually exist on the object because they hadn't been included at the `@implementation`.

**Comment by akovalov** [comment]
@TimSylvester-mousebird both xcframework built from this branch and installed via CocoaPods works good for me, didn't find any issues so far.

**Comment by TimSylvester-mousebird** [comment]
I'm having to make some more changes to deal with integration issues.  Stand by...

**Comment by TimSylvester-mousebird** [comment]
Ok, I think that's about it.  I'm finally able to build it embedded in AutoTester, as an `xcframework`, in `pod lib lint`, and from a client's podfile.  There are a couple of minor breaking changes, but nothing difficult.

**Pull request merged**
